# Generated by Django 5.1.7 on 2025-03-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
