# Generated by Django 5.1.7 on 2025-04-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_subscribe",
            field=models.BooleanField(default=False, verbose_name="Подписка"),
        ),
    ]
