# Generated by Django 5.1.7 on 2025-04-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_subscription_is_subscribe"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
